version: "3"
services:
   react-app:
     restart: always
     build:
       context: ./
       dockerfile: Dockerfile
     image: react-app
     stdin_open: true
     ports:
       - "3000:3000"
     networks:
       - mern-app
     volumes:
       - ./src:/app/src
       - ./app/node_modules

networks:
   mern-app:
     driver: bridge